# GitHub Sponsors funding file
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Moebius Order funding options
github: # Add GitHub Sponsors username if applicable
patreon: moebiusorder
ko_fi: moebiusorder
custom:
  - "https://mcdocs.moebiusorder.com/donate"
  - "https://buymeacoffee.com/moebiusorder"
