name: "✨ Feature Request"
description: Suggest a new topic or improvement to existing documentation
title: "[FEATURE]: "
labels: ["enhancement", "needs-review"]
assignees:
  - Moebius-Order
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest New Content or Improvements
        Help us expand MON CS DOCS with new topics or better explanations.
        
  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What would you like to see?
      options:
        - New Topic
        - New Category
        - Improvement to Existing Topic
        - Additional Examples
        - More Diagrams/Visuals
        - Better Explanations
        - Code Examples
        - Practice Problems
        - Other
    validations:
      required: true

  - type: dropdown
    id: pillar
    attributes:
      label: Knowledge Pillar
      description: Which pillar does this belong to?
      options:
        - Foundational Theory
        - Hardware & Architecture
        - Software Paradigms
        - Systems & Networking
        - Cross-Pillar/General
        - Not Sure
    validations:
      required: true

  - type: input
    id: topic-name
    attributes:
      label: Topic Name
      description: "What should this topic be called?"
      placeholder: "e.g., Red-Black Trees, Virtual Memory, HTTP/3 Protocol"
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: What level is this content?
      options:
        - Beginner
        - Intermediate
        - Advanced
        - Mixed (covers multiple levels)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what content you'd like to see
      placeholder: |
        A comprehensive guide to Red-Black Trees covering:
        - Definition and properties
        - Insertion and deletion algorithms
        - Balancing mechanisms
        - Time complexity analysis
        - Real-world applications
    validations:
      required: true

  - type: textarea
    id: why-important
    attributes:
      label: Why is this Important?
      description: Explain the educational value
      placeholder: |
        This topic is important because:
        - It's commonly taught in university CS courses
        - It's frequently asked in technical interviews
        - It's used in production systems like Linux kernel
    validations:
      required: true

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: What should readers know before learning this?
      placeholder: |
        - Binary Search Trees
        - Tree rotations
        - Basic complexity analysis
    validations:
      required: false

  - type: textarea
    id: related-topics
    attributes:
      label: Related Topics
      description: What other topics connect to this?
      placeholder: |
        - AVL Trees (comparison)
        - B-Trees (similar balancing)
        - Hash Tables (alternative data structure)
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: Reference Materials
      description: Textbooks, papers, or resources you recommend
      placeholder: |
        - Introduction to Algorithms (CLRS) - Chapter 13
        - "A Dichromatic Framework for Balanced Trees" by Guibas & Sedgewick (1978)
    validations:
      required: false

  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would benefit most from this content?
      placeholder: |
        - University CS students (sophomore/junior level)
        - Self-learners preparing for technical interviews
        - Software engineers needing to understand STL implementations
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this?
      options:
        - High (Fundamental CS topic)
        - Medium (Useful but not critical)
        - Low (Nice to have)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Intent
      description: Would you like to help create this?
      options:
        - label: I can write the content
          required: false
        - label: I can provide technical review
          required: false
        - label: I can create diagrams/visuals
          required: false
        - label: I can contribute code examples
          required: false
        - label: I'm just suggesting (someone else should create it)
          required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else we should know?
      placeholder: "This would be particularly helpful for NCERT Class 12 students..."
    validations:
      required: false